#!/bin/bash

RCPATH=/etc/satono
NPREALPATH=/usr/lib/npreal2/driver
LOCALE=ru_RU.UTF-8

. $RCPATH/satono.conf

mkdir -p $LOGPATH/satono
mkdir -p $TMPPATH/satono

add_server()
{
    echo "Adding server $1 ($2 ports)"
    ./mxdelsvr $1
    ./mxaddsvr $1 $2
}

if [ $USE_SERVER == yes ]
then
    modprobe npreal2

    if [ "$1" == "-r" ]
    then
        . $RCPATH/server.conf
        pushd $NPREALPATH > /dev/null
        mkdir -p ./tmp
        if [ "$SERVERS" ]
        then
            for SERVER in $SERVERS
            do
                SERVERNAME=${SERVER%:*}
                PORTS=${SERVER#*:}
                add_server $SERVERNAME $PORTS
            done
        else
            add_server $SERVERNAME $PORTS
        fi
        ./mxloadsvr
        popd > /dev/null
    fi
fi

CMD=""
OP="new-session -d -s satono "
for COMP in `cat $RCPATH/computers.conf`
do
    NAME="`echo $COMP | cut -d- -f2-`"
    NUM="`echo $COMP | cut -d- -f1`"
    CMD="$CMD $OP -n $NAME $TMPPATH/satono/$NUM-$NAME.tmp.sh ;"
    OP="new-window"
    LOGNAME="log.$NUM.$NAME.`date -I`.log"
    echo "while true; do LC_ALL=$LOCALE /usr/bin/minicom -D /dev/${PORTTYPE}${NUM} -C $LOGPATH/satono/$LOGNAME -c on -8 -R UTF-8; done" > $TMPPATH/satono/$NUM-$NAME.tmp.sh
    chmod 755 $TMPPATH/satono/$NUM-$NAME.tmp.sh
done
CMD="$CMD select-window -t :0"
/usr/bin/tmux $CMD
